plugins {
    id 'java'
    id 'org.gradlex.reproducible-builds' version '1.0'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.gradlex.reproducible-builds'

    repositories {
        mavenCentral()
    }

    dependencies {
        compileOnly files("${rootProject.projectDir}/libs/ipscan-any-3.9.2.jar")
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of 21
        }
    }
}
