plugins {
    id 'java'
    id 'org.gradlex.reproducible-builds' version '1.0'
    id 'io.github.sgtsilvio.gradle.proguard' version '0.7.0'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.gradlex.reproducible-builds'
    apply plugin: 'io.github.sgtsilvio.gradle.proguard'

    repositories {
        mavenCentral()
    }

    dependencies {
        compileOnly files("${rootProject.projectDir}/libs/ipscan-any-3.9.2.jar")
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of 17
        }
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            resources.srcDirs = ['resources']
        }
    }

    jar {
        dependsOn check
        from {
            configurations.runtimeClasspath.collect {
                (it.isDirectory() ? it : zipTree(it)).matching {
                    exclude('META-INF/versions/**')
                    exclude('META-INF/maven/**')
                    exclude('META-INF/proguard/**') // not currently used, see https://github.com/Guardsquare/proguard/issues/337
                    exclude('META-INF/LICENSE*')
                }
            }
        }
        duplicatesStrategy = DuplicatesStrategy.FAIL
        includeEmptyDirs = false
    }

    task proguardedJar(type: io.github.sgtsilvio.gradle.proguard.ProguardTask) {
        addInput {
            classpath.from(tasks.jar)
        }
        addOutput {
            archiveFile.set(base.libsDirectory.file("${project.name}-${project.version}-proguarded.jar"))
        }
        addLibrary {
            classpath.from(configurations.compileClasspath)
        }

        jdkModules.add 'java.base'

        rulesFiles.from file("${rootProject.projectDir}/ipscan-plugins.pro")
    }
}
