// SPDX-FileCopyrightText: Copyright (C) 2025 Marek Küthe <m.k@mk16.de>
//
// SPDX-License-Identifier: GPL-3.0-or-later

rootProject.name = 'banduras-ipscan-plugins'

include 'ssh-banner-fetcher', 'mikrotik-routeros-version-fetcher', 'echo-server-fetcher', 'time-protocol-fetcher', 'daytime-protocol-fetcher', 'chargen-fetcher', 'dns-server-fetcher', 'three-type-pinger'
