# SPDX-FileCopyrightText: Copyright (C) 2025 Marek Küthe <m.k@mk16.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

when:
  - event: manual
    branch: main
  - event: push
    branch: main

steps:
  - name: build
    environment:
      IPSCAN_VERSION: 3.9.2
      IPSCAN_CHECKSUM: 42c0d870d1e77df4ac70f11dcf04581a7a5d9cec60773976971d5fd5cb33bd76

    image: codeberg.org/mark22k/ci:latest
    pull: true
    commands:
      - export PATH="$HOME/.local/bin:$PATH"
      - update-alternatives --set java /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
      - update-alternatives --set javac /usr/lib/jvm/temurin-17-jdk-amd64/bin/javac
      - mkdir -p libs
      - cd ..
      - git clone --depth 1 --branch patched https://github.com/marek22k/ipscan.git
      - cd ipscan
      - git tag 3.9.2SVN
      - ./gradlew any
      - cp "build/libs/ipscan-any-3.9.2SVN.jar" "../ipscan-plugins/libs/ipscan-any-3.9.2.jar"
      - cd "../ipscan-plugins"
      - ./gradlew properties
      # - wget --output-document "libs/ipscan-any-$IPSCAN_VERSION.jar" "https://github.com/angryip/ipscan/releases/download/$IPSCAN_VERSION/ipscan-any-$IPSCAN_VERSION.jar"
      # - echo "$IPSCAN_CHECKSUM libs/ipscan-any-$IPSCAN_VERSION.jar" | sha256sum --check --status
      - make check
      - make reuse-lint
      - make lizard
      - make proguardedJar
