# SPDX-FileCopyrightText: Copyright (C) 2025 Marek Küthe <m.k@mk16.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

when:
  - event: tag

steps:
  - name: release
    environment:
      IPSCAN_VERSION: 3.9.2
      IPSCAN_CHECKSUM: 42c0d870d1e77df4ac70f11dcf04581a7a5d9cec60773976971d5fd5cb33bd76

      CODEBERG_GIT_USERNAME:
        from_secret: codeberg_git_username
      CODEBERG_GIT_PASSWORD:
        from_secret: codeberg_git_password
    image: codeberg.org/mark22k/ci:latest
    pull: true
    commands:
      - export PATH="$HOME/.local/bin:$PATH"
      - update-alternatives --set java /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
      - update-alternatives --set javac /usr/lib/jvm/temurin-17-jdk-amd64/bin/javac
      - mkdir -p libs
      - cd ..
      - git clone --depth 1 --branch patched https://github.com/marek22k/ipscan.git
      - cd ipscan
      - git tag 3.9.2SVN
      - ./gradlew any
      - cp "build/libs/ipscan-any-3.9.2SVN.jar" "../ipscan-plugins/libs/ipscan-any-3.9.2.jar"
      - cd "../ipscan-plugins"
      - VERSION=$(./gradlew properties --quiet | grep "^version:" | cut -d' ' -f2)
      # - wget --output-document "libs/ipscan-any-$IPSCAN_VERSION.jar" "https://github.com/angryip/ipscan/releases/download/$IPSCAN_VERSION/ipscan-any-$IPSCAN_VERSION.jar"
      # - echo "$IPSCAN_CHECKSUM libs/ipscan-any-$IPSCAN_VERSION.jar" | sha256sum --check --status
      - make check
      - make reuse-lint
      - make lizard
      - ./gradlew proguardedJar -PskipCheckerFramework
      - |
        for PLUGIN in ssh-banner-fetcher mikrotik-routeros-version-fetcher echo-server-fetcher time-protocol-fetcher daytime-protocol-fetcher chargen-fetcher dns-server-fetcher three-type-pinger
        do
          curl --user $CODEBERG_GIT_USERNAME:$CODEBERG_GIT_PASSWORD --upload-file "$PLUGIN/build/libs/$PLUGIN-$VERSION.jar" "https://codeberg.org/api/packages/mark22k/generic/ipscan-plugins/$VERSION/$PLUGIN-$VERSION.jar"
        done
