name: Coverity Scan

on:
  push:
    branches: [ "github" ]
  schedule:
    - cron: '19 8 * * 5'

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Prepare build
      run: |
        mkdir -p libs
        wget --output-document "libs/ipscan-any-$IPSCAN_VERSION.jar" "https://github.com/angryip/ipscan/releases/download/$IPSCAN_VERSION/ipscan-any-$IPSCAN_VERSION.jar"
        echo "$IPSCAN_CHECKSUM libs/ipscan-any-$IPSCAN_VERSION.jar" | sha256sum --check --status
        ./gradlew properties

    - uses: vapier/coverity-scan-action@v1
      with:
        project: 'ipscan-plugins'
        build_language: 'java'
        command: 'make proguardedJar'
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
