name: Java CI with Gradle

on:
  push:
    branches: [ "github" ]
  pull_request:
    branches: [ "github" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Build ipscan
      run: |
        mkdir -p libs
        cd ..
        git clone --depth 1 --branch patched https://github.com/marek22k/ipscan.git
        cd ipscan
        git tag 3.9.2SVN
        ./gradlew any
        cp "build/libs/ipscan-any-3.9.2SVN.jar" "../ipscan-plugins-mirror/libs/ipscan-any-3.9.2.jar"
        cd "../ipscan-plugins-mirror"
        ./gradlew properties

    - name: Check with Gradle Wrapper
      run: ./gradlew check
    - name: Build with Gradle Wrapper
      run: ./gradlew proguardedJar

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v5
