name: Java CI with Gradle

on:
  push:
    branches: [ "github" ]
  pull_request:
    branches: [ "github" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Prepare build
      run: |
        mkdir -p libs
        wget --output-document "libs/ipscan-any-3.9.3.jar" "https://github.com/angryip/ipscan/releases/download/3.9.3/ipscan-any-3.9.3.jar"
        echo "63a76f8fc8366432d79e62ed8b41cb0719eb469550de6e52bb3f548a80375129 libs/ipscan-any-3.9.3.jar" | sha256sum --check --status
        ./gradlew properties

    - name: Check with Gradle Wrapper
      run: ./gradlew check
    - name: Build with Gradle Wrapper
      run: ./gradlew proguardedJar

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v5
